---
title: "1.2--Add-Prev-Wildfire-as-Treatment"
author: "Elizabeth Buhr"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(root.dir = 'C:/Users/Elizabeth Buhr/Documents/fuels-analysis/')
```

```{r}
#load packages
library(sf) 
library(tidyverse)
library(ggplot2)
```

#Load Geopackage and fires dataset and mtbs

```{r}
#path to file 
intersect_path <- "fuels_analysis.gpkg"

#check layer name
st_layers(intersect_path)

#save the layer
myfires <- st_read(intersect_path, layer = "fires_with_prior_treatment")
```

Load MTBS

```{r}
# Using perimeter data for 1984-2023, should update to include 2024
allfires <- st_read("data/mtbs_perimeter_data/mtbs_perims_DD.shp") %>% 
  st_transform("EPSG:5070") %>% 
  mutate(Ig_Date = as.Date(Ig_Date), YEAR_COMP =year(Ig_Date)) %>%   # convert to date
  filter(Incid_Type=="Wildfire") %>%
  filter(grepl("CO", Event_ID)) %>% #filter out repeated fire names in other states, maybe should use state boundary instead
  st_make_valid(fires)
```


#intersect previous wildfire with fires of interest

```{r}
# Intersect previous and subsequent wildfires
fire_intersect <- st_intersection(myfires, allfires) %>%
  filter(YEAR_COMP < year) %>%
  rename("OBJECTID" = "Event_ID.1", "MGT_TYPE" = "Incid_Type", "EVENT_NAME" = "Incid_Name.1") %>%
  dplyr::select("Event_ID", "irwinID", "Incid_Name", "Map_ID", "year", "OBJECTID", "EVENT_NAME","MGT_TYPE", "YEAR_COMP")
```


#subset mtbs to only previous wildfire
```{r}
# Subset mtbs to only previous wildfire
prior_fires <- allfires %>% 
  filter(Event_ID %in% unique(fire_intersect%>% pull(OBJECTID))) %>%
  rename("OBJECTID" = "Event_ID", "MGT_TYPE" = "Incid_Type", "EVENT_NAME" = "Incid_Name") %>%
  dplyr::select("OBJECTID", "EVENT_NAME","MGT_TYPE", "YEAR_COMP")
```


# load treatment dataset and add previous wildfire 
```{r}
treats <- st_read(intersect_path, layer = "treatments_preceding_fire") %>%
  mutate(OBJECTID = as.character(OBJECTID)) %>%
  rename("geometry" = "geom")

treats <- bind_rows(treats, prior_fires)
```

# add previous wildfire to intersection
```{r}
intersection <- st_read(intersect_path, layer = "intersection") %>%
  mutate(OBJECTID = as.character(OBJECTID))

intersection <- bind_rows(intersection, fire_intersect)
```

# Save new geopackage

```{r}
# copy over my fires layer and start a new geopackage
st_write(
  obj = myfires,
  dsn = "fuels_analysis_v2.gpkg",
  layer = "fires",
  driver = "GPKG",
  delete_dsn = TRUE
)


# write new interactions layer that includes wildfire
st_write(
  obj = intersection,
  dsn = "fuels_analysis_v2.gpkg",
  layer = "intersection",
  driver = "GPKG",
  delete_layer = TRUE
)

# write new treatments layer that includes wildfire
st_write(
  obj = treats,
  dsn = "fuels_analysis_v2.gpkg",
  layer = "treatments",
  driver = "GPKG",
  delete_layer= TRUE
)
```

