---
title: "0a--Data-Download"
author: "Elizabeth Buhr"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
```

# Weather

(maximum temperature, wind velocity, relative humidity, VPD) 
(Palmer Drought Severity Index (PDSI), Energy Release Component, 100- and 1000-hour dead fuel moisture)
FWI? 

```{r}
## Maximum temperature
dir.create(here("data", "raw", "GridMet", "TMax"), showWarnings = FALSE) 
for(j in 2010:2024){ 
  if(!file.exists(here("data", "raw", "GridMet", "TMax", paste0("tmmx_", j, ".nc")))){ 
  temp <- here("data", "raw", "GridMet", "TMax", paste0("tmmx_", j, ".nc")) 
  download.file(paste0("https://www.northwestknowledge.net/metdata/data/tmmx_", j, ".nc"), temp, mode="wb") 
  }
}

## Precipitation
dir.create(here("data", "raw", "GridMet", "PR"), showWarnings = FALSE)
for(j in 2010:2024){
  if(!file.exists(here("data", "raw", "GridMet", "PR", paste0("pr_", j, ".nc")))){
  temp <- here("data", "raw", "GridMet", "PR", paste0("pr_", j, ".nc"))
  download.file(paste0("https://www.northwestknowledge.net/metdata/data/pr_", j, ".nc"), temp, mode="wb")
  }
}

## Wind velocity
dir.create(here("data", "raw", "GridMet", "VS"), showWarnings = FALSE) 
for(j in 2010:2024){ 
  if(!file.exists(here("data", "raw", "GridMet", "VS", paste0("vs_", j, ".nc")))){ 
  temp <- here("data", "raw", "GridMet", "VS", paste0("vs_", j, ".nc")) 
  download.file(paste0("https://www.northwestknowledge.net/metdata/data/vs_", j, ".nc"), temp, mode="wb") 
  }
}

## VPD 
dir.create(here("data", "raw", "GridMet", "VPD"), showWarnings = FALSE)
for(j in 2010:2024){
  if(!file.exists(here("data", "raw", "GridMet", "VPD", paste0("vpd_", j, ".nc")))){
  temp <- here("data", "raw", "GridMet", "VPD", paste0("vpd_", j, ".nc"))
  download.file(paste0("https://www.northwestknowledge.net/metdata/data/vpd_", j, ".nc"), temp, mode="wb")
  }
}

## Palmer Drought Severity Index 
dir.create(here("data", "raw", "GridMet", "PDSI"), showWarnings = FALSE)
for(j in 2010:2024){
  if(!file.exists(here("data", "raw", "GridMet", "PDSI", paste0("pdsi", ".nc")))){
  temp <- here("data", "raw", "GridMet", "PDSI", paste0("pdsi", ".nc"))
  download.file(paste0("https://www.northwestknowledge.net/metdata/data/pdsi", ".nc"), temp, mode="wb")
  }
}

## ERC
dir.create(here("data", "raw", "GridMet", "ERC"), showWarnings = FALSE)
for(j in 2010:2024){
  if(!file.exists(here("data", "raw", "GridMet", "ERC", paste0("erc_", j, ".nc")))){
  temp <- here("data", "raw", "GridMet", "ERC", paste0("erc_", j, ".nc"))
  download.file(paste0("https://www.northwestknowledge.net/metdata/data/erc_", j, ".nc"), temp, mode="wb")
  }
}
```

Daymet

```{r}
test_url <- paste0(
  "https://thredds.daac.ornl.gov/thredds/ncss/ornldaac/2129",
  "/daymet_v4_daily_na_tmax_2020.nc",
  "?var=lat&var=lon&var=tmax",
  "&north=41.10&west=-109.15&east=-101.94&south=36.89",
  "&disableProjSubset=on&horizStride=1",
  "&time_start=2020-01-01T12:00:00Z&time_end=2020-12-31T12:00:00Z",
  "&timeStride=1&accept=netcdf"
)
library(curl)

netrc_path <- file.path(Sys.getenv("USERPROFILE"), "_netrc")
writeLines(c(
  "machine urs.earthdata.nasa.gov",
  "login buhrea0926",
  "password SundayMorning420!"
), netrc_path)

h <- new_handle(netrc = 1, followlocation = TRUE,
                cookiejar = tempfile(), cookiefile = tempfile())

curl_download(test_url, "test_tmax_2020.nc", handle = h)

# verify before trusting it
readLines("test_tmax_2020.nc", n = 2)   # should look like binary garbage, NOT html/text

library(terra)
r <- rast("test_tmax_2020.nc")
plot(r[[1]])
```

# Pre-Fire Fuels

```{r}
# Canopy Cover
if(!dir.exists( here("data", "raw", "LANDFIRE", "US_105_CC"))){
  temp <- here("data", "raw", "LANDFIRE", "US_105_CC.zip")
  download.file("https://landfire.gov/data-downloads/US_105/US_105_CC.zip", temp, mode="wb")
  unzip(temp, exdir=here("data", "raw", "LANDFIRE"))
  file.remove(temp)
}
```

